### PR TITLE
add build_platforms

### PR DESCRIPTION
**Pull request by gschramm**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by gschramm** [comment]
@conda-forge-admin, please rerender

**Comment by gschramm** [comment]
@xhochy any idea why the tests fail for the `osx_arm64` builds? Is that expected because we are using `cross compilation`?

**Comment by xhochy** [comment]
Yes, there is no cross-compilation but no emulator. Thus you need to add `test: native_and_emulated` to `conda-forge.yml` and rerender.

**Comment by gschramm** [comment]
@conda-forge-admin, please rerender

**Comment by gschramm** [comment]
> Yes, there is no cross-compilation but no emulator. Thus you need to add `test: native_and_emulated` to `conda-forge.yml` and rerender.

Forgot to re-render ...

Thanks a lot for all your help! Your efforts (and the efforts of all the other conda-forgers) are much appreciated!

**Pull request merged**
